### ISSUE TITLE
Lack of input formatting and sanity checking

### ISSUE THREAD

**Issue by Matthew-Bradley** [DongerZonie/CountPeopleSlacking#1]
As of right now the slackbot will absolutely any string input, whether it contains letters, numbers, spaces or special characters. This should be constrained to whole, integer numbers greater than (or equal) to zero. Anything not formatted as such a number should be rejected.

The check could consist of taking the string input, removing all spaces (and other unprinted delimiting characters, like tabs), and ensuring all remaining characters are numeric (0-9) before converting to an integer. A further check could include ensuring the count doesn't exceed some physical maximum, ie 250 people.

**Comment by DongerZonie** [comment]
All non-numeric text input rejected. Sanity checking for impossible values will not happen to allow scaling of the app.
