### ISSUE TITLE
Missing space and incorrect capitalization in output formatting.

### ISSUE THREAD

**Issue by Matthew-Bradley** [DongerZonie/CountPeopleSlacking#2]
There is a space missing and incorrect capitalization in the output of the bot when responding to messages.

For example,
"Hey monica.wu,You just added..."
should be formatted as
"Hey monica.wu, you just added..."
in this case with an additional space and a lowercase 'y' after it.

**Comment by DongerZonie** [comment]
This is an artifact of the Outgoing Webhook integration and is working as intended, in order to only reply to users that replied to the people count request.
